import type { BaseTile, WhitelistedPair, TilesetMetaData } from "@/tilesets";

const tilesMod = import.meta.glob<string>("./*.png", {
  import: "default",
  eager: true,
});

export const tilesetData: TilesetMetaData = {
  name: "circles",
  designerName: "Mario Klingemann",
  designerSocial: "https://twitter.com/quasimondo",
};

export const baseTileset: BaseTile[] = [
  {
    name: "b",
    path: tilesMod["./b.png"],
  },
  {
    name: "b_half",
    path: tilesMod["./b_half.png"],
    timesCanBeRotated: 3,
  },
  {
    name: "b_i",
    path: tilesMod["./b_i.png"],
    timesCanBeRotated: 1,
  },
  {
    name: "b_quarter",
    path: tilesMod["./b_quarter.png"],
    timesCanBeRotated: 3,
  },
  {
    name: "w",
    path: tilesMod["./w.png"],
  },
  {
    name: "w_half",
    path: tilesMod["./w_half.png"],
    timesCanBeRotated: 3,
  },
  {
    name: "w_i",
    path: tilesMod["./w_i.png"],
    timesCanBeRotated: 1,
  },
  {
    name: "w_quarter",
    path: tilesMod["./w_quarter.png"],
    timesCanBeRotated: 3,
  },
];

export const baseWhitelist: WhitelistedPair[] = [
  { left: "b", right: "b" },
  { left: "b", right: "b_half 1" },
  { left: "b", right: "b_i 1" },
  { left: "b", right: "b_quarter 1" },
  { left: "b", right: "b_quarter 2" },
  { left: "b", right: "w_half" },
  { left: "b", right: "w_half 2" },
  { left: "b", right: "w_half 3" },
  { left: "b", right: "w_i" },
  { left: "b", right: "w_quarter" },
  { left: "b", right: "w_quarter 3" },
  { left: "b_half", right: "b_half" },
  { left: "b_half", right: "b_half 2" },
  { left: "b_half", right: "b_half 3" },
  { left: "b_half", right: "b_i" },
  { left: "b_half", right: "b_quarter" },
  { left: "b_half", right: "b_quarter 3" },
  { left: "b_half", right: "w" },
  { left: "b_half", right: "w_half 1" },
  { left: "b_half", right: "w_i 1" },
  { left: "b_half", right: "w_quarter 1" },
  { left: "b_half", right: "w_quarter 2" },
  { left: "b_half 1", right: "b_half 3" },
  { left: "b_half 1", right: "b_i" },
  { left: "b_half 1", right: "b_quarter" },
  { left: "b_half 1", right: "b_quarter 3" },
  { left: "b_half 1", right: "w" },
  { left: "b_half 1", right: "w_half 1" },
  { left: "b_half 1", right: "w_i 1" },
  { left: "b_half 1", right: "w_quarter 1" },
  { left: "b_half 1", right: "w_quarter 2" },
  { left: "b_half 2", right: "b_half" },
  { left: "b_half 2", right: "b_half 3" },
  { left: "b_half 2", right: "b_i" },
  { left: "b_half 2", right: "b_quarter" },
  { left: "b_half 2", right: "b_quarter 3" },
  { left: "b_half 2", right: "w" },
  { left: "b_half 2", right: "w_half 1" },
  { left: "b_half 2", right: "w_i 1" },
  { left: "b_half 2", right: "w_quarter 1" },
  { left: "b_half 2", right: "w_quarter 2" },
  { left: "b_half 3", right: "b_half 1" },
  { left: "b_half 3", right: "b_i 1" },
  { left: "b_half 3", right: "b_quarter 1" },
  { left: "b_half 3", right: "b_quarter 2" },
  { left: "b_half 3", right: "w_half" },
  { left: "b_half 3", right: "w_half 2" },
  { left: "b_half 3", right: "w_half 3" },
  { left: "b_half 3", right: "w_i" },
  { left: "b_half 3", right: "w_quarter" },
  { left: "b_half 3", right: "w_quarter 3" },
  { left: "b_i", right: "b_i" },
  { left: "b_i", right: "b_quarter" },
  { left: "b_i", right: "b_quarter 3" },
  { left: "b_i", right: "w" },
  { left: "b_i", right: "w_half 1" },
  { left: "b_i", right: "w_i 1" },
  { left: "b_i", right: "w_quarter 1" },
  { left: "b_i", right: "w_quarter 2" },
  { left: "b_i 1", right: "b_i 1" },
  { left: "b_i 1", right: "b_quarter 1" },
  { left: "b_i 1", right: "b_quarter 2" },
  { left: "b_i 1", right: "w_half" },
  { left: "b_i 1", right: "w_half 2" },
  { left: "b_i 1", right: "w_half 3" },
  { left: "b_i 1", right: "w_i" },
  { left: "b_i 1", right: "w_quarter" },
  { left: "b_i 1", right: "w_quarter 3" },
  { left: "b_quarter", right: "b_quarter 1" },
  { left: "b_quarter", right: "b_quarter 2" },
  { left: "b_quarter", right: "w_half" },
  { left: "b_quarter", right: "w_half 2" },
  { left: "b_quarter", right: "w_half 3" },
  { left: "b_quarter", right: "w_i" },
  { left: "b_quarter", right: "w_quarter" },
  { left: "b_quarter", right: "w_quarter 3" },
  { left: "b_quarter 1", right: "b_quarter" },
  { left: "b_quarter 1", right: "b_quarter 3" },
  { left: "b_quarter 2", right: "w" },
  { left: "b_quarter 1", right: "w_half 1" },
  { left: "b_quarter 1", right: "w_i 1" },
  { left: "b_quarter 1", right: "w_quarter 1" },
  { left: "b_quarter 1", right: "w_quarter 2" },
  { left: "b_quarter 2", right: "b_quarter" },
  { left: "b_quarter 2", right: "w" },
  { left: "b_quarter 2", right: "w_half 1" },
  { left: "b_quarter 2", right: "w_i 1" },
  { left: "b_quarter 2", right: "w_quarter 1" },
  { left: "b_quarter 2", right: "w_quarter 2" },
  { left: "b_quarter 3", right: "w_quarter 1" },
  { left: "b_quarter 3", right: "w_half" },
  { left: "b_quarter 3", right: "w_half 2" },
  { left: "b_quarter 3", right: "w_half 3" },
  { left: "b_quarter 3", right: "w_i" },
  { left: "b_quarter 3", right: "w_quarter" },
  { left: "b_quarter 3", right: "w_quarter 3" },
  { left: "w", right: "w" },
  { left: "w", right: "w_half 1" },
  { left: "w", right: "w_i 1" },
  { left: "w", right: "w_quarter 1" },
  { left: "w", right: "w_quarter 2" },
  { left: "w_half", right: "w_half" },
  { left: "w_half", right: "w_half 2" },
  { left: "w_half", right: "w_half 3" },
  { left: "w_half", right: "w_i" },
  { left: "w_half", right: "w_quarter" },
  { left: "w_half", right: "w_quarter 3" },
  { left: "w_half 1", right: "w_half 3" },
  { left: "w_half 1", right: "w_i" },
  { left: "w_half 1", right: "w_quarter" },
  { left: "w_half 1", right: "w_quarter 3" },
  { left: "w_half 2", right: "w_quarter" },
  { left: "w_half 2", right: "w_half 3" },
  { left: "w_half 2", right: "w_i" },
  { left: "w_half 2", right: "w_quarter" },
  { left: "w_half 2", right: "w_quarter 3" },
  { left: "w_half 3", right: "w_half 1" },
  { left: "w_half 3", right: "w_i 1" },
  { left: "w_half 3", right: "w_quarter 1" },
  { left: "w_half 3", right: "w_quarter 2" },
  { left: "w_i", right: "w_i" },
  { left: "w_i", right: "w_quarter" },
  { left: "w_i", right: "w_quarter 3" },
  { left: "w_i 1", right: "w_i 1" },
  { left: "w_i 1", right: "w_quarter 1" },
  { left: "w_i 1", right: "w_quarter 2" },
  { left: "w_quarter", right: "w_quarter 1" },
  { left: "w_quarter", right: "w_quarter 2" },
  { left: "w_quarter 1", right: "w_quarter" },
  { left: "w_quarter 1", right: "w_quarter 3" },
  { left: "w_quarter 2", right: "w_quarter" },
  { left: "w_quarter 3", right: "w_quarter 1" },
];
