import type { BaseTile, WhitelistedPair, TilesetMetaData } from "@/tilesets";

const tilesMod = import.meta.glob<string>("./*.png", {
  import: "default",
  eager: true,
});

export const tilesetData: TilesetMetaData = {
  name: "rooms",
  designerName: "Maxin Gumin",
  designerSocial: "https://twitter.com/exutumno",
};

const baseTileset: BaseTile[] = [
  {
    name: "bend",
    path: tilesMod["./bend.png"],
    timesCanBeRotated: 3,
    weight: 0.5,
  },
  {
    name: "corner",
    path: tilesMod["./corner.png"],
    timesCanBeRotated: 3,
    weight: 0.5,
  },
  {
    name: "corridor",
    path: tilesMod["./corridor.png"],
    timesCanBeRotated: 1,
  },
  {
    name: "door",
    path: tilesMod["./door.png"],
    timesCanBeRotated: 3,
    weight: 0.5,
  },
  {
    name: "empty",
    path: tilesMod["./empty.png"],
  },
  {
    name: "side",
    path: tilesMod["./side.png"],
    timesCanBeRotated: 3,
    weight: 2.0,
  },
  {
    name: "t",
    path: tilesMod["./t.png"],
    timesCanBeRotated: 3,
    weight: 0.5,
  },
  {
    name: "turn",
    path: tilesMod["./turn.png"],
    timesCanBeRotated: 3,
    weight: 0.25,
  },
  {
    name: "wall",
    path: tilesMod["./wall.png"],
  },
];

const baseWhitelist: WhitelistedPair[] = [
  { left: "bend", right: "bend 1" },
  { left: "bend", right: "corner 2" },
  { left: "bend", right: "door 2" },
  { left: "bend", right: "side" },
  { left: "bend 1", right: "empty" },
  { left: "bend 2", right: "empty" },
  { left: "bend 3", right: "bend 2" },
  { left: "bend 3", right: "corner 1" },
  { left: "bend 3", right: "door" },
  { left: "bend 3", right: "side 2" },
  { left: "corner", right: "door" },
  { left: "corner", right: "side 2" },
  { left: "corner 1", right: "corner" },
  { left: "corner 1", right: "corner 3" },
  { left: "corner 1", right: "side 1" },
  { left: "corner 1", right: "t 1" },
  { left: "corner 1", right: "turn" },
  { left: "corner 1", right: "turn 3" },
  { left: "corner 1", right: "wall" },
  { left: "corner 2", right: "corner" },
  { left: "corner 2", right: "side 1" },
  { left: "corner 2", right: "t 1" },
  { left: "corner 2", right: "turn" },
  { left: "corner 2", right: "wall" },
  { left: "corner 3", right: "door 2" },
  { left: "corner 3", right: "side" },
  { left: "corridor", right: "side 1" },
  { left: "corridor", right: "wall" },
  { left: "corridor 1", right: "corridor 1" },
  { left: "corridor 1", right: "door 3" },
  { left: "corridor 1", right: "t" },
  { left: "corridor 1", right: "t 2" },
  { left: "corridor 1", right: "t 3" },
  { left: "corridor 1", right: "turn 1" },
  { left: "corridor 1", right: "turn 2" },
  { left: "door", right: "side 2" },
  { left: "door 1", right: "door 3" },
  { left: "door 1", right: "t" },
  { left: "door 1", right: "t 2" },
  { left: "door 1", right: "t 3" },
  { left: "door 1", right: "turn 1" },
  { left: "door 1", right: "turn 2" },
  { left: "door 2", right: "side" },
  { left: "door 3", right: "empty" },
  { left: "empty", right: "empty" },
  { left: "empty", right: "side 3" },
  { left: "side", right: "side" },
  { left: "side 3", right: "side 1" },
  { left: "side 3", right: "t 1" },
  { left: "side 3", right: "turn" },
  { left: "side 3", right: "turn 3" },
  { left: "side 3", right: "wall" },
  { left: "t", right: "t 2" },
  { left: "t", right: "turn 1" },
  { left: "t", right: "turn 2" },
  { left: "t 2", right: "turn 1" },
  { left: "t 2", right: "turn 2" },
  { left: "t 3", right: "wall" },
  { left: "turn", right: "turn 1" },
  { left: "turn", right: "turn 2" },
  { left: "turn 1", right: "wall" },
  { left: "turn 2", right: "wall" },
  { left: "turn 3", right: "turn 1" },
  { left: "wall", right: "wall" },
];

export { baseTileset, baseWhitelist };
