import type { BaseTile, WhitelistedPair, TilesetMetaData } from "@/tilesets";

const tilesMod = import.meta.glob<string>("./*.png", {
  import: "default",
  eager: true,
});

export const tilesetData: TilesetMetaData = {
  name: "circuit",
  designerName: "Maxin Gumin",
  designerSocial: "https://twitter.com/exutumno",
};

const baseTileset: BaseTile[] = [
  {
    name: "bridge",
    path: tilesMod["./bridge.png"],
    timesCanBeRotated: 1,
  },
  {
    name: "component",
    path: tilesMod["./component.png"],
    weight: 20,
  },
  {
    name: "connection",
    path: tilesMod["./connection.png"],
    timesCanBeRotated: 3,
    weight: 10,
  },
  {
    name: "corner",
    path: tilesMod["./corner.png"],
    timesCanBeRotated: 3,
    weight: 10,
  },
  {
    name: "dskew",
    path: tilesMod["./dskew.png"],
    timesCanBeRotated: 1,
    weight: 2,
  },
  {
    name: "skew",
    path: tilesMod["./skew.png"],
    timesCanBeRotated: 3,
    weight: 2,
  },
  {
    name: "substrate",
    path: tilesMod["./substrate.png"],
    weight: 2,
  },
  {
    name: "t",
    path: tilesMod["./t.png"],
    timesCanBeRotated: 3,
    weight: 0.1,
  },
  {
    name: "track",
    path: tilesMod["./track.png"],
    timesCanBeRotated: 1,
    weight: 2,
  },
  {
    name: "transition",
    path: tilesMod["./transition.png"],
    timesCanBeRotated: 3,
    weight: 0.4,
  },
  {
    name: "viad",
    path: tilesMod["./viad.png"],
    timesCanBeRotated: 1,
    weight: 0.1,
  },
  {
    name: "vias",
    path: tilesMod["./vias.png"],
    timesCanBeRotated: 3,
    weight: 0.3,
  },
  {
    name: "wire",
    path: tilesMod["./wire.png"],
    timesCanBeRotated: 1,
    weight: 0.5,
  },
];

const baseWhitelist: WhitelistedPair[] = [
  { left: "bridge", right: "bridge" },
  { left: "bridge", right: "transition 1" },
  { left: "bridge", right: "wire" },
  { left: "bridge 1", right: "bridge 1" },
  { left: "bridge 1", right: "connection 1" },
  { left: "bridge 1", right: "dskew" },
  { left: "bridge 1", right: "dskew 1" },
  { left: "bridge 1", right: "skew 1" },
  { left: "bridge 1", right: "skew 2" },
  { left: "bridge 1", right: "t" },
  { left: "bridge 1", right: "t 2" },
  { left: "bridge 1", right: "t 3" },
  { left: "bridge 1", right: "track 1" },
  { left: "bridge 1", right: "transition 3" },
  { left: "bridge 1", right: "viad" },
  { left: "bridge 1", right: "vias 1" },
  { left: "component", right: "component" },
  { left: "component", right: "connection 3" },
  { left: "connection", right: "connection" },
  { left: "connection", right: "corner" },
  { left: "connection 2", right: "corner 3" },
  { left: "connection 3", right: "dskew" },
  { left: "connection 3", right: "dskew 1" },
  { left: "connection 3", right: "skew 1" },
  { left: "connection 3", right: "skew 2" },
  { left: "connection 3", right: "t" },
  { left: "connection 3", right: "t 2" },
  { left: "connection 3", right: "t 3" },
  { left: "connection 3", right: "track 1" },
  { left: "corner", right: "corner 1" },
  { left: "corner", right: "corner 2" },
  { left: "corner", right: "skew" },
  { left: "corner", right: "skew 3" },
  { left: "corner", right: "substrate" },
  { left: "corner", right: "t 1" },
  { left: "corner", right: "track" },
  { left: "corner", right: "transition" },
  { left: "corner", right: "transition 2" },
  { left: "corner", right: "viad 1" },
  { left: "corner", right: "vias" },
  { left: "corner", right: "vias 2" },
  { left: "corner", right: "wire 1" },
  { left: "corner 3", right: "corner 1" },
  { left: "corner 3", right: "corner 2" },
  { left: "corner 3", right: "skew" },
  { left: "corner 3", right: "skew 3" },
  { left: "corner 3", right: "substrate" },
  { left: "corner 3", right: "t 1" },
  { left: "corner 3", right: "track" },
  { left: "corner 3", right: "transition" },
  { left: "corner 3", right: "transition 2" },
  { left: "corner 3", right: "viad 1" },
  { left: "corner 3", right: "vias" },
  { left: "corner 3", right: "vias 2" },
  { left: "corner 3", right: "wire 1" },
  { left: "dskew", right: "dskew" },
  { left: "dskew", right: "skew 2" },
  { left: "dskew", right: "t" },
  { left: "dskew", right: "t 2" },
  { left: "dskew", right: "t 3" },
  { left: "dskew", right: "track 1" },
  { left: "dskew", right: "transition 3" },
  { left: "dskew", right: "viad" },
  { left: "dskew", right: "vias 1" },
  { left: "dskew 1", right: "dskew 1" },
  { left: "dskew 1", right: "skew 1" },
  { left: "dskew 1", right: "t" },
  { left: "dskew 1", right: "t 2" },
  { left: "dskew 1", right: "t 3" },
  { left: "dskew 1", right: "track 1" },
  { left: "dskew 1", right: "transition 3" },
  { left: "dskew 1", right: "viad" },
  { left: "dskew 1", right: "vias 1" },
  { left: "skew", right: "skew 2" },
  { left: "skew", right: "t" },
  { left: "skew", right: "t 2" },
  { left: "skew", right: "t 3" },
  { left: "skew", right: "track 1" },
  { left: "skew", right: "transition 3" },
  { left: "skew", right: "viad" },
  { left: "skew", right: "vias 1" },
  { left: "skew 1", right: "skew" },
  { left: "skew 1", right: "skew 3" },
  { left: "skew 1", right: "substrate" },
  { left: "skew 1", right: "t 1" },
  { left: "skew 1", right: "track" },
  { left: "skew 1", right: "transition" },
  { left: "skew 1", right: "transition 2" },
  { left: "skew 1", right: "viad 1" },
  { left: "skew 1", right: "vias" },
  { left: "skew 1", right: "vias 3" },
  { left: "skew 1", right: "wire 1" },
  { left: "skew 2", right: "skew" },
  { left: "skew 2", right: "substrate" },
  { left: "skew 2", right: "t 1" },
  { left: "skew 2", right: "track" },
  { left: "skew 2", right: "transition" },
  { left: "skew 2", right: "transition 2" },
  { left: "skew 2", right: "viad 1" },
  { left: "skew 2", right: "vias" },
  { left: "skew 2", right: "vias 3" },
  { left: "skew 2", right: "wire 1" },
  { left: "skew 3", right: "skew 1" },
  { left: "skew 3", right: "t" },
  { left: "skew 3", right: "t 2" },
  { left: "skew 3", right: "t 3" },
  { left: "skew 3", right: "track 1" },
  { left: "skew 3", right: "transition 3" },
  { left: "skew 3", right: "viad" },
  { left: "skew 3", right: "vias 1" },
  { left: "substrate", right: "substrate" },
  { left: "substrate", right: "t 1" },
  { left: "substrate", right: "track" },
  { left: "substrate", right: "transition" },
  { left: "substrate", right: "transition 2" },
  { left: "substrate", right: "viad 1" },
  { left: "substrate", right: "vias" },
  { left: "substrate", right: "vias 2" },
  { left: "substrate", right: "wire 1" },
  { left: "t", right: "t" },
  { left: "t", right: "t 2" },
  { left: "t", right: "t 3" },
  { left: "t", right: "track 1" },
  { left: "t", right: "transition 3" },
  { left: "t", right: "viad" },
  { left: "t", right: "vias 1" },
  { left: "t 1", right: "t" },
  { left: "t 1", right: "t 2" },
  { left: "t 1", right: "t 3" },
  { left: "t 1", right: "track 1" },
  { left: "t 1", right: "transition 3" },
  { left: "t 1", right: "viad" },
  { left: "t 1", right: "vias 1" },
  { left: "t 2", right: "t" },
  { left: "t 2", right: "track 1" },
  { left: "t 2", right: "transition 3" },
  { left: "t 2", right: "viad" },
  { left: "t 2", right: "vias 1" },
  { left: "t 3", right: "track" },
  { left: "t 3", right: "transition" },
  { left: "t 3", right: "transition 2" },
  { left: "t 3", right: "viad 1" },
  { left: "t 3", right: "vias" },
  { left: "t 3", right: "vias 2" },
  { left: "t 3", right: "wire 1" },
  { left: "track", right: "track" },
  { left: "track", right: "transition" },
  { left: "track", right: "transition 2" },
  { left: "track", right: "viad 1" },
  { left: "track", right: "vias" },
  { left: "track", right: "vias 2" },
  { left: "track", right: "wire 1" },
  { left: "track 1", right: "track 1" },
  { left: "track 1", right: "transition 3" },
  { left: "track 1", right: "viad" },
  { left: "track 1", right: "vias 1" },
  { left: "transition", right: "transition" },
  { left: "transition", right: "transition 2" },
  { left: "transition", right: "viad 1" },
  { left: "transition", right: "vias" },
  { left: "transition", right: "vias 2" },
  { left: "transition", right: "wire 1" },
  { left: "transition 2", right: "transition" },
  { left: "transition 2", right: "viad 1" },
  { left: "transition 2", right: "vias" },
  { left: "transition 2", right: "vias 2" },
  { left: "transition 2", right: "wire 1" },
  { left: "transition 3", right: "wire" },
  { left: "viad 1", right: "viad 1" },
  { left: "viad 1", right: "vias" },
  { left: "viad 1", right: "vias 2" },
  { left: "viad 1", right: "wire 1" },
  { left: "vias", right: "vias" },
  { left: "vias", right: "vias 2" },
  { left: "vias", right: "vias 3" },
  { left: "vias", right: "wire 1" },
  { left: "vias 1", right: "vias" },
  { left: "vias 1", right: "vias 2" },
  { left: "vias 1", right: "vias 3" },
  { left: "vias 1", right: "wire 1" },
  { left: "vias 2", right: "vias" },
  { left: "vias 2", right: "wire 1" },
  { left: "wire", right: "wire" },
  { left: "wire 1", right: "wire 1" },
];

export { baseTileset, baseWhitelist };
